os: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - set VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\

build_script:
  - ps: |
      # Install-Module VSSetup -Scope CurrentUser -Force
      # $vs = (Get-VSSetupInstance)[0]
      # $vs | fl *
      # $vs.Packages | where {$_.Id -like '*NuGet*'} | ft
      # $vs.Packages | where {$_.Id -like '*FSharp*'} | ft

  # - .\.nuget\NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile .\.nuget\NuGet.Config
  # - msbuild /t:restore .\src\fsharp\Fsc\Fsc.fsproj /v:diag

  - build.cmd release publicsign

test: off
version: '{build}'
artifacts:
  - path: release
    name: release